Nostralogia3/Models/Geo/CoordinatesModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace Nostralogia3.Models.Geo
{
    public class CoordinatesModel : PlaceDataCommon
    {

       // public bool IsDecimal { get; set; }

        #region DECIMAL
        [DisplayName("Longitude")]
        public double Longitude { get; set; }
        [DisplayName("Latitude")]
        public double Latitude { get; set; }
        #endregion
        #region Min_Sec
        public int LongDegrees { get; set; }
        public int LongMinutes { get; set; }
        public int LongSeconds { get; set; }
        public int LatDegrees { get; set; }
        public int LatMinutes { get; set; }
        public int LatSeconds { get; set; }
        #endregion

        public List<SelectListItem> NS { get; set; }
        public List<SelectListItem> WE { get; set; }
        public List<SelectListItem> CoordFormats { get; set; }
        public string LongSemiSphere { get; set; }
        public string LatSemiSphere { get; set; }
        public string LongSemiSphere2 { get; set; }
        public string LatSemiSphere2 { get; set; }
        public short CoordFormatSelected { get; set; }

        public CoordinatesModel()
        {
            MainLabel = "Coordinates:";
            InitCombos();
        }
        public CoordinatesModel(string mainlabel)
        {
            MainLabel = mainlabel;
            InitCombos();
        }
        public override void InitCombos()
        {
            NS = new List<SelectListItem>()
            {
                new SelectListItem(){Text="Select...",Value="0",Selected=true},
                new SelectListItem(){Text="N",Value="1"},
                new SelectListItem(){Text="S",Value="-1"}
            };
            WE = new List<SelectListItem>()
            {
                new SelectListItem(){Text="Select...",Value="0",Selected=true},
                new SelectListItem(){Text="E",Value="1"},
                new SelectListItem(){Text="W",Value="-1"}
            };
            CreateCoordFormatCollection();
        }
        protected void CreateCoordFormatCollection()
        {
            CoordFormats = new List<SelectListItem>()
            {
                new SelectListItem()
                {
                    Text= "Decimal degrees",
                    Value="1"
                },
                new SelectListItem()
                {
                    Text= "Degrees/Minutes/Seconds",
                    Value="2",
                    Selected=true
                }
            };
            CoordFormatSelected = 2;
        }
        public override bool SaveData()
        {
            return false ;
        }
        public double GetLongitude()
        {
            int ilong = int.Parse(LongSemiSphere=="0"? LongSemiSphere2: LongSemiSphere);
            double vallong = Longitude;
            if(CoordFormatSelected==2)
            {
                vallong = LongDegrees + LongMinutes / 60.0 + LongSeconds / 3600.0;
            }
            return vallong * ilong;

        }
        public double GetLaitude()
        {
            int ilat = int.Parse(LatSemiSphere == "0" ? LatSemiSphere2 : LatSemiSphere);
            double vallat = Latitude;
            if (CoordFormatSelected==2)
            {
                vallat = LatDegrees + LatMinutes / 60.0 + LatSeconds / 3600.0;
            }
            return vallat * ilat;
        }
    }
}

Nostralogia3/Models/Geo/CountriesStatesCommon.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Nostralogia3.Models.Factories;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace Nostralogia3.Models.Geo
{
    public class CountriesStatesCommon : PlaceDataCommon
    {
        [DisplayName("Country")]
        public short? CountryId { get; set; }
        [DisplayName("State/Province/Land")]
        public int? StateId { get; set; }

        public List<SelectListItem> Countries { get; protected set; }
        public List<SelectListItem> States { get; protected set; }
        public override void InitCombos()
        {
            FillUpCountries();
            States = new List<SelectListItem>();
        }

        public override bool SaveData()
        {
            return false;
        }
        protected void FillUpCountries()
        {
            GeoFactory fact = new GeoFactory();
            Countries = fact.GetCountriesListCollection();
            Countries.Insert(0, new SelectListItem()
            {
                Text = Constants.Values.ZeroStringComboText,
                Value = Constants.Values.ZeroStringComboValue
            });
            SelectListItem item = Countries.FirstOrDefault(x => x.Value == CountryId.ToString());
            if (item != null)
            {
                item.Selected = true;
            }
        }

    }
}

Nostralogia3/Models/Geo/EventPlaceModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Nostralogia3.Models.Factories;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace Nostralogia3.Models.Geo
{
    public class EventPlaceModel : CountriesStatesCommon
    {
        [DisplayName("City/Town/Village")]
        public int? PlaceId { get; set; }



        public List<SelectListItem> Cities { get; protected set; }

        public bool ReadOnly { get; protected set; }

        public EventPlaceModel()
        {

        }
        public EventPlaceModel(string label)
        {
           InitCombos();
            MainLabel = label;
            ReadOnly = false;

        }
        public EventPlaceModel(int cityId, string label, bool readOnly)
        {
            MainLabel = label;
            ReadOnly = readOnly;
            int idState = 0;
            int idCountry = 0;
            GeoFactory fact = new GeoFactory();
            fact.GetCountryStateByCity(cityId,out idCountry,out idState);
            FillUpAll((short)idCountry, idState, cityId);
        }
        public EventPlaceModel(short? countryId, int? stateId, int? cityId, string label, bool readOnly)
        {
            ReadOnly = readOnly;
            MainLabel = label;
            FillUpAll(countryId, stateId, cityId);
        }
        protected void FillUpAll(short? countryId, int? stateId, int? cityId)
        {
            CountryId = countryId ?? 0;
            StateId = stateId ?? 0;
            PlaceId = cityId ?? 0;

            FillUpCountries();
            if (CountryId > 0)
            {
                UpdateStates();
            }
            else
            {
                States = new List<SelectListItem>();
                Cities = new List<SelectListItem>();
            }
            if (StateId > 0)
            {
                UpdateCitiesByStates();
            }
            else if (Cities == null)
            {
                Cities = new List<SelectListItem>();
            }

        }

        public void UpdateStates()
        {
            GeoFactory fact = new GeoFactory();
            List<List<SelectListItem>> list = fact.GetStatesCitiesByCountry(CountryId);
            States = list[0];
            if (StateId > 0)
            {
                SelectListItem item = States.FirstOrDefault(x => x.Value == StateId.ToString());
                if(item!=null)
                {
                    item.Selected = true;
                    
                }
            }
            else
            {
                Cities = list[1];
                if (PlaceId > 0)
                {
                    SelectListItem item = Cities.FirstOrDefault(x => x.Value == PlaceId.ToString());
                    if (item != null)
                    {
                        item.Selected = true;
                    }
                }
            }
        }
        public void UpdateCitiesByStates()
        {
            GeoFactory fact = new GeoFactory();
            Cities = fact.GetCitiesListCollection(0,(int)StateId);
            if (PlaceId > 0)
            {

                SelectListItem item = Cities.FirstOrDefault(x => x.Value == PlaceId.ToString());
                if (item != null)
                {
                    item.Selected = true;
                }
            }
        }

        public void InidData(int id)
        {
            throw new NotImplementedException();
        }

        public override void InitCombos()
        {
            base.InitCombos();
            
            Cities = new List<SelectListItem>();
        }

        public override bool SaveData()
        {
            return false;
        }
    }
}

Nostralogia3/Models/Geo/ExpansionModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace Nostralogia3.Models.Geo
{
    public class ExpansionModel : CountriesStatesCommon
    {

        public List<SelectListItem> SelectedIGeoItemsCollection { get; set; } = new();
        public override bool SaveData()
        {
            return false;
        }
        public ExpansionModel() { }
        public ExpansionModel(string label)
        {
            InitCombos();
            MainLabel = label;
        }
    }
}

Nostralogia3/Models/Geo/HistoryEventPlaceModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Nostralogia3.Models.Geo
{
    public class HistoryEventPlaceModel: EventPlaceModel
    {
        public HistoryEventPlaceModel()
        {

        }
        public HistoryEventPlaceModel(string label)
            :base(label)
        {
        }
        public HistoryEventPlaceModel(int cityId, string label, bool readOnly)
            :base(cityId, label, readOnly)
        {
        }
        public HistoryEventPlaceModel(short? countryId, int? stateId, int? cityId, string label, bool readOnly)
            :base(countryId, stateId, cityId, label, readOnly)
        {
        }
        public override bool SaveData()
        {
            return false;
        }
    }
}

Nostralogia3/Models/Geo/PlaceDataCommon.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Nostralogia3.Models.Geo
{
    public abstract class PlaceDataCommon
    {
        public enum PlaceDataType
        {
            City=1,
            Coordinates,
            Expansion
        }
        
        public string MainLabel { get; set; }
        public abstract void InitCombos();
        public abstract bool SaveData();
    }
}

Nostralogia3/ViewModels/Geo/AddCityVM.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Nostralogia3.Common;
using Nostralogia3.Models.Factories;
using Nostralogia3.Models.Geo;
using NostralogiaDAL.NostraGeoEntities;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Nostralogia3.ViewModels.Geo
{
    public class AddCityVM : ViewModelBase 
    {
        public short CountryRef { get; set; } = 0;
        public int StateRegionRef { get; set; } = 0;
        public string CityName { get; set; }
        public CoordinatesModel Coordinates { get; set; }   = new CoordinatesModel();
        public short TimeZone { get; set; }
        
        public List<SelectListItem> StatesRegions { get; set; }=new List<SelectListItem>();
        public List<SelectListItem> Countries { get; set; }
        public List<SelectListItem> TimeZonesCollection { get; set; }
        public AddCityVM()
        {
            GeoFactory fact = new GeoFactory();
            
            Countries = fact.GetCountriesListCollection();
            TimeZonesCollection = fact.GetTimeZones();
          
        }
        protected void SetStatesCollections()
        {
            GeoFactory fact = new GeoFactory();
            StatesRegions = fact.GetStatesListCollection(CountryRef);
        }
        public async Task<bool> AddCity()
        {
            GeoFactory fact = new GeoFactory();
            City ct = new City()
            {
                CityName = CityName,
                Country = CountryRef,
                Latitude = Coordinates.GetLaitude(),
                Longitude = Coordinates.GetLongitude(),
                RegionState = StateRegionRef<0? 0: StateRegionRef,
                TimeZone = TimeZone
            };
            int err= await fact.AddCity(ct);
            //if(err>0)
            //{
            //    ErrMessagesCollection errcol = new ErrMessagesCollection();
            //    ErrorMessage = errcol.GetMessage(err);
            //}
            return err== (int)ErrMessagesCollection.Errors.NoErrors;
        }

    }
}

Nostralogia3/ViewModels/Geo/AddCountryVM.cs
using Nostralogia3.Models.Factories;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;

namespace Nostralogia3.ViewModels.Geo
{
    public class AddCountryVM :ViewModelBase
    {
        [DisplayName("Enter a country name")]
        public string CountryName { get; set; }
        [DisplayName("Enter an acronym")]
        public string CountryAcr { get; set; }


        public async Task<bool> AddCountry()
        {
            GeoFactory fact = new GeoFactory();
            return await fact.AddCountry(CountryName,CountryAcr);            
        }
    }
}

Nostralogia3/ViewModels/Geo/AddStateProvinceVM.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Nostralogia3.Models.Factories;
using System.Collections.Generic;
using System.ComponentModel;
using System.Threading.Tasks;

namespace Nostralogia3.ViewModels.Geo
{
    public class AddStateProvinceVM
    {
        [DisplayName("Enter a State/Province name")]
        public string ProvinceName { get; set; }
        [DisplayName("Enter an acronym")]
        public string ProvinceAcr { get; set; }
        [DisplayName("Select a Country")]
        public short CountryRef { get; set; }
        public List<SelectListItem> Countries { get; protected set; }

        public AddStateProvinceVM()
        {
            GetCountryCollection();
        }
        protected void GetCountryCollection()
        {
            GeoFactory fact = new GeoFactory();
            Countries=fact.GetCountriesListCollection();
        }
        public async Task<bool> AddStateProvince()
        {
            GeoFactory fact = new GeoFactory();
            return await fact.AddStateProvince(ProvinceName, ProvinceAcr, CountryRef);
        }
    }
}

Nostralogia3/Controllers/Geo/GeoController.cs
using Microsoft.AspNetCore.Mvc;
using Nostralogia3.ViewModels.Geo;
using System.Threading.Tasks;

namespace Nostralogia3.Controllers.Geo
{
    public class GeoController : BaseController
    {
        public IActionResult AddCountry()
        {
            AddCountryVM model = new AddCountryVM();
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> AddCountry(AddCountryVM model)
        {
            bool brez = false;
            if(ModelState.IsValid)
            {
                brez = await model.AddCountry();
            }
            if (brez)
            {
                return RedirectToAction("HomePage", "Home");
            }
            else
            {
                return RedirectToAction("AddCountry");
            }
        }
        public IActionResult AddStateProvince()
        {
            AddStateProvinceVM model = new AddStateProvinceVM();
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> AddStateProvince(AddStateProvinceVM model)
        {
            bool brez = false;
            if (ModelState.IsValid)
            {
                brez = await model.AddStateProvince();
            }
            if (brez)
            {
                return RedirectToAction("HomePage", "Home");
            }
            else
            {
                return RedirectToAction("AddStateProvince");
            }
        }
        public IActionResult AddCity()
        {
            AddCityVM model = new AddCityVM();
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> AddCity(AddCityVM model)
        {
            bool brez = false;
            if (ModelState.IsValid)
            {
                brez = await model.AddCity();
            }
            if (brez)
            {
                return RedirectToAction("HomePage", "Home");
            }
            else
            {
                return RedirectToAction("AddStateProvince");
            }
        }
    }
}

Nostralogia3/Views/Geo/AddCity.cshtml
@{
    ViewData["Title"] = "DataPerson";
    Layout = "~/Views/Shared/_Layout2.cshtml";
    
}
@using Nostralogia3.Extensions
@model Nostralogia3.ViewModels.Geo.AddCityVM
<div class="container bg-light">
    <h2 class="container">Add New City</h2>
    <form method="post" asp-action="AddCity" asp-controller="Geo">

            <div class="row">
                <div class="form-group col-md-3">
                   <label class="required"><span class="field-name"></span>&nbsp;<strong class="required">Select a country</strong></label>
                    @Html.DropDownListFor(x => x.CountryRef, Model.Countries, new { @class = "form-control min_width_combo", id="cmbCountries" })
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-3">
                   <label class="required"><span class="field-name"></span>&nbsp;<strong class="required">Select a State/Province</strong></label>
                   @Html.DropDownListFor(x => x.StateRegionRef, Model.StatesRegions, new { @class = "form-control min_width_combo", id="cmbStates" })
                </div>
            </div>


            <div class="row">
                <div class="form-group col-md-3">
                    <label class="required"><span class="field-name"></span>&nbsp;<strong class="required">City Name</strong></label>
                    <input asp-for="@Model.CityName" asp- class="form-control" data-val="true" data-val-required="The City name field is required" type="text" value="" required="required"/>
                </div>
            </div>
        @await Html.PartialAsync("~/Views/UserControls/_EventCoordinatesView.cshtml", Model.Coordinates, nameof(Model.Coordinates))

           <div class="row mt-lg-3">
                <div class="form-group col-md-3">
                   <label class="required"><span class="field-name"></span>&nbsp;<strong class="required">Select a Time Zone</strong></label>
                    @Html.DropDownListFor(x => x.TimeZone, Model.TimeZonesCollection, new { @class = "form-control min_width_combo" })
                </div>
            </div>

             <div class="row mt-lg-5">
                <div class="form-group ml-lg-4">
                    <button type="submit" class="nostr_btn">Add City</button>
                </div>    
                <div class="form-group">
                    <input type="button" value="Cancel" onclick="location.href='@Url.Action("HomePage", "Home")'" class="nostr_btn" />
                </div>
            </div>
        </form>
</div>
    <script src="/JS/GeoActions.js"></script>
    <script>
        $(document).ready(function () {


        $("#cmbCountries").on("change", function () {
            UpdateCountry();
        });
        $("#cmbStates").on("change", function () {
            UpdateStates();
        });

     });

    </script>

Nostralogia3/Views/Geo/AddCountry.cshtml
@{
    ViewData["Title"] = "New Country";
    Layout = "~/Views/Shared/_Layout2.cshtml";
    
}
@model Nostralogia3.ViewModels.Geo.AddCountryVM
<div class="container bg-light nostra_container">
    <h2>Add New Country Data</h2>
<form method="post" asp-action="AddCountry" asp-controller="Geo">
        <div class="row">
            <div class="form-group col-md-3">
                <label class="required"><span class="field-name"></span>&nbsp;<strong class="required">Country Name</strong></label>
                <input asp-for="@Model.CountryName" asp- class="form-control" data-val="true" data-val-required="The Country Name field is required." id="CountryName" name="CountryName" type="text" value="" required="required"/>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-3">
                <label class="required"><span class="field-name"></span>&nbsp;<strong class="required">Country Acronym</strong></label>
                <input asp-for="@Model.CountryAcr" asp- class="form-control" data-val="true" data-val-required="The Acronym field is required." id="CountryAcr" name="CountryAcr" type="text" value="" required="required"/>
            </div>
        </div>

         <div class="row mt-lg-5">
            <div class="form-group ml-lg-4">
                <button type="submit" class="nostr_btn">Add Country</button>
            </div>    
            <div class="form-group">
                <input type="button" value="Cancel" onclick="location.href='@Url.Action("HomePage", "Home")'" class="nostr_btn" />
            </div>
        </div>
    </form>
</div>

Nostralogia3/Views/Geo/AddStateProvince.cshtml
@{
    ViewData["Title"] = "New State/Province";
    Layout = "~/Views/Shared/_Layout2.cshtml";
    
}

@model Nostralogia3.ViewModels.Geo.AddStateProvinceVM
<div class="container bg-light nostra_container">
    <h2>Add New State/Province Data</h2>
    <form method="post" asp-action="AddStateProvince" asp-controller="Geo">

            <div class="row">
                <div class="form-group col-md-3">
                   <label class="required"><span class="field-name"></span>&nbsp;<strong class="required">Select a country</strong></label>
                    @Html.DropDownListFor(x => x.CountryRef, Model.Countries, new { @class = "form-control min_width_combo" })
                </div>
            </div>

            <div class="row">
                <div class="form-group col-md-3">
                    <label class="required"><span class="field-name"></span>&nbsp;<strong class="required">State/Province Name</strong></label>
                    <input asp-for="@Model.ProvinceName" asp- class="form-control" data-val="true" data-val-required="The Province Name field is required." type="text" value="" required="required"/>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-3">
                    <label class="required"><span class="field-name"></span>&nbsp;<strong class="required">State/Province Acronym</strong></label>
                    <input asp-for="@Model.ProvinceAcr" asp- class="form-control" data-val="true" data-val-required="The Acronym field is required."  type="text" value="" required="required"/>
                </div>
            </div>


             <div class="row mt-lg-5">
                <div class="form-group ml-lg-4">
                    <button type="submit" class="nostr_btn">Add Province</button>
                </div>    
                <div class="form-group">
                    <input type="button" value="Cancel" onclick="location.href='@Url.Action("HomePage", "Home")'" class="nostr_btn" />
                </div>
            </div>
        </form>

</div>